In [3]:
import numpy as np

In [5]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([6, 7, 8, 9, 10])
v3 = np.array(5)
print(v1.shape)

(5,)


In [ ]:
class Student:
    def __init__(self, name, age) -> None:
        
        self._name = name
        self.age = age
    @property
    def name(self):
        return f"{self._name} "

In [16]:
s1 = Student("Fahd", 21)
s1.name

'Fahd '

In [17]:
vec = np.array([1, 2, 3, 4, 5, 6])
mat = vec.reshape(2, 3)
print(mat)

[[1 2 3]
 [4 5 6]]


In [ ]:
vec = np.array([1, 2, 3, 4])
mat = vec.reshape((vec.shape[0],1))
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [20]:
vec = np.array([1, 2, 3, 4])
mat = vec[ : ,None]
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [23]:
def array_reshape(arr, row = -1, cols= -1):
    try:
        arr = np.array(arr)
        return arr.reshape((row, cols))
    except Exception as e:
        raise ValueError("Invalid reshape operations: {e}")
    return arr.reshape((row, cols))                 

In [29]:
vec = [1, 2, 3, 4 ,5 ,6]
print("test 1(2*3 matrix):", array_reshape(vec, 2, 3))

test 1(2*3 matrix): [[1 2 3]
 [4 5 6]]


In [32]:
class c:
    x=3
o1 = c()

In [36]:
mat = np.array([[3, 2, 6],
                [4, 5, True]])
fmat = mat.astype(str)
print(fmat)
print(fmat.dtype)

[['3' '2' '6']
 ['4' '5' '1']]
<U21


In [37]:
v = np.array([1, 2, 3, 4])
v[-2]

np.int64(3)

In [41]:
m = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
            [10, 11, 12]])
m[-3:-1, -3:-1]


array([[4, 5],
       [7, 8]])

In [39]:
v = np.array([1, 2, 3, 4])
v[2:5]

array([3, 4])

In [43]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],])
mat_transpose = mat.T
mat_transpose


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [44]:
mat = np.zeros((3, 3))
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
mat = np.ones((3, 3))
mat

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
mean_filter = np.full((3, 3), 5)
mean_filter


array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [47]:
mean_filter = np.empty((3, 3))
mean_filter


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
angles = np.array([0, 30, 45, 60, 90])
angles

array([ 0, 30, 45, 60, 90])

In [49]:
vec = np.linspace(0, 10, num=10)
vec

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [50]:
I = np.identity(3, dtype=float)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
import random
np.random.rand(3, 3)

array([[0.96242467, 0.08864542, 0.78490115],
       [0.52194478, 0.95507546, 0.98363978],
       [0.16191954, 0.42275478, 0.57687369]])

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5,6],])
a.shape


(1, 6)

In [17]:
a = ['fahd','sherif','taha']
np.random.choice(a, size=(3,4))

array([['taha', 'sherif', 'fahd', 'sherif'],
       ['taha', 'fahd', 'taha', 'taha'],
       ['sherif', 'sherif', 'sherif', 'fahd']], dtype='<U6')

In [21]:
mat1 = np.ones((3,4))
mat2 = np.zeros((5,3))

np.savez('file_test.npz',ones_mat = mat1 , zeros_mat =mat2)

In [ ]:
with np.load('file_test.npz')as file:
    mat1 = file['ones_mat']
    mat2 = file['zeros_mat']

In [24]:
print(mat1)
print("=======================")
print(mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
m1 = np.array([
    [1, 2, 3],
    [0, 0, 0]
])

m2 = np.array([
    [5, 6, 37],
    [1, 1, 1]
])

mat3 = np.hstack((m1,m2))
mat3

array([[ 1,  2,  3,  5,  6, 37],
       [ 0,  0,  0,  1,  1,  1]])

In [33]:
s = 4
v = np.array([2,4,3,4,10])
# v==s
v.__eq__(s)
v.__lt__

<method-wrapper '__lt__' of numpy.ndarray object at 0x000001CAABB73ED0>

In [40]:
v = np.array([1, 2, 3, 4, 5])
np.any(v>1)

np.True_

In [42]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([2, 3, 0, 5, 3])
np.allclose(v1 , v2, atol=1)

False

In [ ]:
def is_close(v1, v2)-> bool:
    np.allclose(v1 , v2, atol=1)
    np.allclose(v1 , v2, atol=1)
    np.allclose(v1 , v2, atol=1)


In [45]:
v = np.array([2, 4, 6, 10])
condition = v>=4
v[condition] = -1
print(v)

[ 2 -1 -1 -1]


In [ ]:
v11 = np.array([1,2,3])
c = 2
summaion = v11 +c
multiplication = v11 *c
print(summaion)
print(multiplication)

[3 4 5]
[2 4 6]
